# Generated by Django 5.1.4 on 2026-05-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_role'),
        ('stafftracking', '0002_alter_stafflocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflocation',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='myapp.register'),
        ),
    ]
