# Generated by Django 6.0.5 on 2026-05-14 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('card_number', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=10)),
                ('cvc', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
