# Generated by Django 5.1.4 on 2026-05-17 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_role'),
        ('payment', '0002_alter_userpayment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
    ]
