# Generated by Django 5.1.4 on 2026-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdashboard', '0002_alter_stafftask_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftask',
            old_name='waste_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='stafftask',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stafftask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stafftask',
            name='staff',
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
