# Generated by Django 5.1.4 on 2026-05-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdashboard', '0003_rename_waste_type_stafftask_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
