# Generated by Django 5.1.4 on 2026-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('STAFF', 'STAFF'), ('ADMIN', 'ADMIN')], default='USER', max_length=10),
        ),
    ]
