# Generated by Django 5.1.4 on 2026-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_userrequest_delete_userwasterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
