# Generated by Django 5.1.4 on 2026-05-17 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_role'),
        ('request', '0003_alter_userrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequests', to='myapp.register'),
        ),
    ]
