# Generated by Django 5.1.4 on 2026-05-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_userrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='PENDING', max_length=20),
        ),
    ]
