# Generated by Django 6.0.5 on 2026-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('STAFF', 'STAFF'), ('ADMIN', 'ADMIN')], max_length=20)),
            ],
        ),
    ]
